# Generated by Django 6.0.4 on 2026-04-09 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=200)),
                ('service_interest', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(help_text='e.g. Composite Materials, CNC Fabrication, Workshop Training', max_length=100)),
                ('product_interest', models.CharField(blank=True, default='', max_length=200)),
                ('specifications', models.TextField(help_text='Detailed technical requirements')),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('material_preferences', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('timeline', models.CharField(blank=True, default='', help_text='e.g. Urgent, 1-2 Weeks, 1 Month', max_length=50)),
                ('budget_range', models.CharField(blank=True, default='', max_length=50)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='quote_attachments/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='quote_attachments/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='quote_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('QUOTED', 'Quoted'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
