# Generated by Django 6.0.4 on 2026-05-28 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdocument_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('PARTICIPANT', 'Workshop Participant'), ('SCHOOL', 'School')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Class/Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(limit_choices_to={'role': 'SCHOOL'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
