# Generated by Django 6.0.4 on 2026-04-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('FABRICATION', 'Fabrication'), ('MATERIAL_SUPPLY', 'Material Supply'), ('DEVELOPMENT', 'Development'), ('TRAINING', 'Training'), ('RESEARCH', 'Research')], max_length=20)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('challenges', models.TextField(blank=True, default='', help_text='Challenges faced during the project')),
                ('solutions', models.TextField(blank=True, default='', help_text='Solutions implemented')),
                ('technologies_used', models.JSONField(default=list, help_text='List of technologies used')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_active', models.BooleanField(default=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
