# Generated by Django 6.0.4 on 2026-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior (Class 4-8)'), ('senior', 'Senior (Class 9-12)')], default='junior', max_length=20),
        ),
    ]
