# Generated by Django 6.0.4 on 2026-05-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='workshop_gallery/')),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='workshops.workshopcategory')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Workshop Gallery Image',
                'verbose_name_plural': 'Workshop Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
