# Generated by Django 6.0.4 on 2026-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specs',
            field=models.JSONField(default=dict, help_text="Per-variant specs e.g. {gsm: 100, width_mm: 1000, thickness_mm: 0.13, weave: 'Plain'}"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(help_text='e.g. BhorForce® PC100', max_length=100),
        ),
    ]
